name: My First Workflow (in this repo)

on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in directory
        run: |
          echo "The repo ${{ github.repository }} contains:"
          tree
